# My Movie-Watching Stats

[This code complements my blogpost visualizing my movie-watching stats. Check it out here!](https://muhammadali.xyz/my-movie-stats-visualized/)

I will briefly talk though my step belows and why I'm taking them.

In [1]:
import pandas as pd
import numpy as np

omdb_key = 'xxxxxx' #OMDb API key here

Let's import my IMDb ratings data. You can get your's by going to IMDb > Lists > Your Ratings and exporting that.

Of course, this requires that you have been consistently rating movies.

In [2]:
imdb_df = pd.read_csv('data/ratings.csv', encoding = "ISO-8859-1") #Read IMDb ratings export CSV
imdb_df.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,"Animation, Action, Comedy, Family, Sci-Fi",223442,2010-10-28,Tom McGrath
1,tt0100685,7,2014-05-04,State of Grace,https://www.imdb.com/title/tt0100685/,movie,7.2,134.0,1990,"Action, Crime, Drama, Romance, Thriller",20444,1990-09-14,Phil Joanou
2,tt1010048,8,2011-05-06,Slumdog Millionaire,https://www.imdb.com/title/tt1010048/,movie,8.0,120.0,2008,"Drama, Romance",787410,2008-08-30,"Loveleen Tandan, Danny Boyle"
3,tt1013752,6,2011-05-09,Fast & Furious,https://www.imdb.com/title/tt1013752/,movie,6.6,107.0,2009,"Action, Thriller",258307,2009-03-12,Justin Lin
4,tt1014759,6,2011-11-14,Alice in Wonderland,https://www.imdb.com/title/tt1014759/,movie,6.4,108.0,2010,"Adventure, Family, Fantasy",377320,2010-02-25,Tim Burton

In [3]:
imdb_df['Title Type'].unique() #Check what types of titles are there

array(['movie', 'tvMiniSeries', 'tvSeries', 'video', 'tvMovie'],
      dtype=object)

In [4]:
imdb_movies = imdb_df[imdb_df['Title Type'] == 'movie'] #Filter out only the 'movie' type
imdb_movies.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,"Animation, Action, Comedy, Family, Sci-Fi",223442,2010-10-28,Tom McGrath
1,tt0100685,7,2014-05-04,State of Grace,https://www.imdb.com/title/tt0100685/,movie,7.2,134.0,1990,"Action, Crime, Drama, Romance, Thriller",20444,1990-09-14,Phil Joanou
2,tt1010048,8,2011-05-06,Slumdog Millionaire,https://www.imdb.com/title/tt1010048/,movie,8.0,120.0,2008,"Drama, Romance",787410,2008-08-30,"Loveleen Tandan, Danny Boyle"
3,tt1013752,6,2011-05-09,Fast & Furious,https://www.imdb.com/title/tt1013752/,movie,6.6,107.0,2009,"Action, Thriller",258307,2009-03-12,Justin Lin
4,tt1014759,6,2011-11-14,Alice in Wonderland,https://www.imdb.com/title/tt1014759/,movie,6.4,108.0,2010,"Adventure, Family, Fantasy",377320,2010-02-25,Tim Burton

Now that I have my IMDb data, we see it doesn't have all the information. Particularly, information like actors.

I will use the [OMDb API](http://www.omdbapi.com/) to get some more data. It's free for up to 1000 calls a day, which fits my dataset.

In [8]:
url = 'http://www.omdbapi.com/?apikey='+omdb_key+'&i='
omdb_movies = pd.DataFrame() #Blank dataframe to append OMDb data to
for i in imdb_movies['Const']: #Loop through all the movie IDs
    omdb_movies = omdb_movies.append(pd.read_json(url+i)) #Get API JSON data as dataframe and append to omdb_movies

# omdb_movies = pd.read_csv('output/omdb_export.csv') #Use this if API data already saved
omdb_movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Megamind,2010,PG,05 Nov 2010,95 min,"Animation, Action, Comedy, Family, Sci-Fi",Tom McGrath,"Alan Schoolcraft, Brent Simons","Will Ferrell, Brad Pitt, Tina Fey, Jonah Hill",The supervillain Megamind finally defeats his ...,...,63.0,7.2,"223,114",tt1001526,movie,25 Feb 2011,"$148,244,405",Paramount Studios/DWA,NaN,True
1,Megamind,2010,PG,05 Nov 2010,95 min,"Animation, Action, Comedy, Family, Sci-Fi",Tom McGrath,"Alan Schoolcraft, Brent Simons","Will Ferrell, Brad Pitt, Tina Fey, Jonah Hill",The supervillain Megamind finally defeats his ...,...,63.0,7.2,"223,114",tt1001526,movie,25 Feb 2011,"$148,244,405",Paramount Studios/DWA,NaN,True
2,Megamind,2010,PG,05 Nov 2010,95 min,"Animation, Action, Comedy, Family, Sci-Fi",Tom McGrath,"Alan Schoolcraft, Brent Simons","Will Ferrell, Brad Pitt, Tina Fey, Jonah Hill",The supervillain Megamind finally defeats his ...,...,63.0,7.2,"223,114",tt1001526,movie,25 Feb 2011,"$148,244,405",Paramount Studios/DWA,NaN,True
3,State of Grace,1990,R,14 Sep 1990,134 min,"Action, Crime, Drama, Romance, Thriller",Phil Joanou,Dennis McIntyre,"Sean Penn, Ed Harris, Gary Oldman, Robin Wright",A New York cop is recruited to return to his h...,...,60.0,7.2,"20,358",tt0100685,movie,03 Dec 2002,NaN,Orion Pictures Corporation,NaN,True
4,State of Grace,1990,R,14 Sep 1990,134 min,"Action, Crime, Drama, Romance, Thriller",Phil Joanou,Dennis McIntyre,"Sean Penn, Ed Harris, Gary Oldman, Robin Wright",A New York cop is recruited to return to his h...,...,60.0,7.2,"20,358",tt0100685,movie,03 Dec 2002,NaN,Orion Pictures Corporation,NaN,True

We get each movie multiple times; that's because the Ratings column has a dictionary. Each dictionary item gets added as a new row.

I will save a CSV of the OMDb data, so I don't need to run the API again on the same dataset.

In [9]:
omdb_movies.to_csv('output/omdb_export.csv', index=False)

In [10]:
omdb_movies.dtypes

Title          object
Year            int64
Rated          object
Released       object
Runtime        object
Genre          object
Director       object
Writer         object
Actors         object
Plot           object
Language       object
Country        object
Awards         object
Poster         object
Ratings        object
Metascore     float64
imdbRating    float64
imdbVotes      object
imdbID         object
Type           object
DVD            object
BoxOffice      object
Production     object
Website       float64
Response         bool
dtype: object

I only care about imdb ratings, which we already have as a column.

Let's get rid of the duplicates

In [11]:
omdb_movies_final = omdb_movies.drop_duplicates('imdbID')
omdb_movies_final.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Megamind,2010,PG,05 Nov 2010,95 min,"Animation, Action, Comedy, Family, Sci-Fi",Tom McGrath,"Alan Schoolcraft, Brent Simons","Will Ferrell, Brad Pitt, Tina Fey, Jonah Hill",The supervillain Megamind finally defeats his ...,...,63.0,7.2,"223,114",tt1001526,movie,25 Feb 2011,"$148,244,405",Paramount Studios/DWA,NaN,True
3,State of Grace,1990,R,14 Sep 1990,134 min,"Action, Crime, Drama, Romance, Thriller",Phil Joanou,Dennis McIntyre,"Sean Penn, Ed Harris, Gary Oldman, Robin Wright",A New York cop is recruited to return to his h...,...,60.0,7.2,"20,358",tt0100685,movie,03 Dec 2002,NaN,Orion Pictures Corporation,NaN,True
6,Slumdog Millionaire,2008,R,25 Dec 2008,120 min,"Drama, Romance","Danny Boyle, Loveleen Tandan(co-director)","Simon Beaufoy (screenplay), Vikas Swarup (novel)","Dev Patel, Saurabh Shukla, Anil Kapoor, Raj Zu...",A Mumbai teenager reflects on his life after b...,...,84.0,8.0,"785,456",tt1010048,movie,31 Mar 2009,"$141,243,551",Fox Searchlight Pictures,NaN,True
9,Fast & Furious,2009,PG-13,03 Apr 2009,107 min,"Action, Thriller",Justin Lin,"Chris Morgan, Gary Scott Thompson (characters)","Vin Diesel, Paul Walker, Jordana Brewster, Mic...","Brian O'Conner, back working for the FBI in Lo...",...,46.0,6.6,"257,984",tt1013752,movie,27 Jul 2009,"$155,022,220",Universal Pictures,NaN,True
12,Alice in Wonderland,2010,PG,05 Mar 2010,108 min,"Adventure, Family, Fantasy",Tim Burton,"Linda Woolverton (screenplay), Lewis Carroll (...","Johnny Depp, Mia Wasikowska, Helena Bonham Car...",Nineteen-year-old Alice returns to the magical...,...,53.0,6.4,"377,027",tt1014759,movie,01 Jun 2010,"$319,323,000",Walt Disney Pictures,NaN,True

In [12]:
#Create master df with all the fields we want
all_movies = imdb_movies.merge(
    omdb_movies_final[['imdbID', 'Writer', 'Actors', 'Plot', 'Language', 'Country', 'Poster', 'Metascore', 'BoxOffice']],
    how = 'left',
    left_on = 'Const',
    right_on = 'imdbID'
)
all_movies.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,...,Directors,imdbID,Writer,Actors,Plot,Language,Country,Poster,Metascore,BoxOffice
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,"Animation, Action, Comedy, Family, Sci-Fi",...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons","Will Ferrell, Brad Pitt, Tina Fey, Jonah Hill",The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
1,tt0100685,7,2014-05-04,State of Grace,https://www.imdb.com/title/tt0100685/,movie,7.2,134.0,1990,"Action, Crime, Drama, Romance, Thriller",...,Phil Joanou,tt0100685,Dennis McIntyre,"Sean Penn, Ed Harris, Gary Oldman, Robin Wright",A New York cop is recruited to return to his h...,English,"UK, USA",https://m.media-amazon.com/images/M/MV5BMjEyNT...,60.0,NaN
2,tt1010048,8,2011-05-06,Slumdog Millionaire,https://www.imdb.com/title/tt1010048/,movie,8.0,120.0,2008,"Drama, Romance",...,"Loveleen Tandan, Danny Boyle",tt1010048,"Simon Beaufoy (screenplay), Vikas Swarup (novel)","Dev Patel, Saurabh Shukla, Anil Kapoor, Raj Zu...",A Mumbai teenager reflects on his life after b...,"English, Hindi, French, German","UK, USA",https://m.media-amazon.com/images/M/MV5BZmNjZW...,84.0,"$141,243,551"
3,tt1013752,6,2011-05-09,Fast & Furious,https://www.imdb.com/title/tt1013752/,movie,6.6,107.0,2009,"Action, Thriller",...,Justin Lin,tt1013752,"Chris Morgan, Gary Scott Thompson (characters)","Vin Diesel, Paul Walker, Jordana Brewster, Mic...","Brian O'Conner, back working for the FBI in Lo...","English, Spanish","USA, Japan",https://m.media-amazon.com/images/M/MV5BYjQ1ZT...,46.0,"$155,022,220"
4,tt1014759,6,2011-11-14,Alice in Wonderland,https://www.imdb.com/title/tt1014759/,movie,6.4,108.0,2010,"Adventure, Family, Fantasy",...,Tim Burton,tt1014759,"Linda Woolverton (screenplay), Lewis Carroll (...","Johnny Depp, Mia Wasikowska, Helena Bonham Car...",Nineteen-year-old Alice returns to the magical...,English,"USA, UK",https://m.media-amazon.com/images/M/MV5BMTMwNj...,53.0,"$319,323,000"

In [13]:
#There are columns with comma separated strings; let's split them out into a row each
all_movies = all_movies.assign(Genres=all_movies['Genres'].str.split(',')).explode('Genres') #Split Genres
all_movies = all_movies.assign(Directors=all_movies['Directors'].str.split(',')).explode('Directors') #Split Directors
all_movies = all_movies.assign(Actors=all_movies['Actors'].str.split(',')).explode('Actors') #Split Actors
all_movies = all_movies.assign(Language=all_movies['Language'].str.split(',')).explode('Language') #Split Languages

all_movies.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,...,Directors,imdbID,Writer,Actors,Plot,Language,Country,Poster,Metascore,BoxOffice
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Brad Pitt,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Tina Fey,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Jonah Hill,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Action,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"

In [16]:
#Explode caused some columns to have extra whitespaces; let's fix that
all_movies['Genres'] = all_movies['Genres'].str.strip()
all_movies['Directors'] = all_movies['Directors'].str.strip()
all_movies['Actors'] = all_movies['Actors'].str.strip()
all_movies['Language'] = all_movies['Language'].str.strip()
all_movies.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,...,Directors,imdbID,Writer,Actors,Plot,Language,Country,Poster,Metascore,BoxOffice
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Brad Pitt,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Tina Fey,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Jonah Hill,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Action,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"

I have split the languages into separate rows too; but I only want to keep the primary language. So I will remove duplicate rows based on the other unique columns I want to keep.

Since the primary language will be the first row for each, the additional rows will be dropped.

In [20]:
all_movies = all_movies.drop_duplicates(['Const', 'Genres', 'Directors', 'Actors'])
all_movies.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,...,Directors,imdbID,Writer,Actors,Plot,Language,Country,Poster,Metascore,BoxOffice
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Brad Pitt,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Tina Fey,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Jonah Hill,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Action,...,Tom McGrath,tt1001526,"Alan Schoolcraft, Brent Simons",Will Ferrell,The supervillain Megamind finally defeats his ...,English,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405"

The above is pretty much all I needed. However, some filters I was trying to create in Google Data Studio were breaking (looks like a bug to me, because the filters work in the Explorer).

To counter that bug, I unfortunately need to take some extra steps which I would have ideally used GDS calculated fields for.

I want a "Favourite Score" for actors, directors and genres. I will calculate this by taking the square of my average rating and multiplying that by the number of movies for each actor/director/genre.

I am squaring it to increase the influence of the rating, otherwise a lesser rated actor who appears in more movies will impact the score.

In [21]:
#Create unique actors dataframe with Actor Score

all_actors = all_movies.groupby(['Actors']).agg({'Your Rating': ['mean'], 'IMDb Rating': ['mean'], 'Const': ['nunique']})
all_actors['Actor Score'] = np.power(all_actors['Your Rating']['mean'], 2) * all_actors['Const']['nunique']
all_actors.columns = all_actors.columns.droplevel(1)
all_actors.rename(columns={"Const": "Actor Count"}, inplace=True)
all_actors.head()

               Your Rating  IMDb Rating  Actor Count  Actor Score
Actors
50 Cent           6.555556     6.555556            2    85.950617
Aaliyah           6.000000     6.100000            1    36.000000
Aamir Bashir      6.000000     8.100000            1    36.000000
Aamir Khan        7.666667     8.066667            5   293.888889
Aaron Eckhart     7.400000     7.520000            4   219.040000

In [22]:
#Create unique directors dataframe with Director Score

all_directors = all_movies.groupby(['Directors']).agg({'Your Rating': ['mean'], 'IMDb Rating': ['mean'], 'Const': ['nunique']})
all_directors['Director Score'] = np.power(all_directors['Your Rating']['mean'], 2) * all_directors['Const']['nunique']
all_directors.columns = all_directors.columns.droplevel(1)
all_directors.rename(columns={"Const": "Director Count"}, inplace=True)
all_directors.head()

                 Your Rating  IMDb Rating  Director Count  Director Score
Directors
Aamir Khan          8.000000     8.400000               1       64.000000
Aaron Schneider     7.000000     7.000000               1       49.000000
Aaron Sorkin        7.000000     7.400000               1       49.000000
Adam Kassen         7.000000     6.800000               1       49.000000
Adam McKay          7.142857     7.285714               2      102.040816

In [23]:
#Create unique genres dataframe with Genre Score

all_genres = all_movies.groupby(['Genres']).agg({'Your Rating': ['mean'], 'IMDb Rating': ['mean'], 'Const': ['nunique']})
all_genres['Genre Score'] = np.power(all_genres['Your Rating']['mean'], 2) * all_genres['Const']['nunique']
all_genres.columns = all_genres.columns.droplevel(1)
all_genres.rename(columns={"Const": "Genre Count"}, inplace=True)
all_genres.head()

           Your Rating  IMDb Rating  Genre Count   Genre Score
Genres
Action        6.887550     6.864458          472  22390.900147
Adventure     7.123839     7.092879          277  14057.495778
Animation     7.439560     7.370330           52   2878.047096
Biography     7.463636     7.420000          108   6016.233719
Comedy        6.876984     7.040476          206   9742.339601

I have everything I need now. I will join everything into one large dataframe.

In [24]:
favourites = all_movies.copy()
favourites = favourites.merge(all_actors[['Actor Count', 'Actor Score']], how='left', left_on = 'Actors', right_index = True)
favourites = favourites.merge(all_directors[['Director Count', 'Director Score']], how='left', left_on = 'Directors', right_index = True)
favourites = favourites.merge(all_genres[['Genre Count', 'Genre Score']], how='left', left_on = 'Genres', right_index = True)
favourites.head()

,Const,Your Rating,Date Rated,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,...,Country,Poster,Metascore,BoxOffice,Actor Count,Actor Score,Director Count,Director Score,Genre Count,Genre Score
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405",4,157.388430,2,84.5,52,2878.047096
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405",22,1243.936920,2,84.5,52,2878.047096
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405",2,85.950617,2,84.5,52,2878.047096
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Animation,...,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405",8,369.170036,2,84.5,52,2878.047096
0,tt1001526,7,2011-04-12,Megamind,https://www.imdb.com/title/tt1001526/,movie,7.2,95.0,2010,Action,...,USA,https://m.media-amazon.com/images/M/MV5BMTAzMz...,63.0,"$148,244,405",4,157.388430,2,84.5,472,22390.900147

In [25]:
#Output all final data
favourites.to_csv("output/all_movies.csv", index = False)

## All Done!

Hope you enjoyed my process! Leave a [comment on my blog](https://muhammadali.xyz/my-movie-stats-visualized/) with your thoughts :)